! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE GETGRBOBSTRCT(BLK2GLO, BLK2LOC, IREAD, NPR, FILNM, KFILE_HANDLE, KGRIB_HANDLE)

!****  *GETGRBOBSTRCT* - DETERMINES OBSTRUCTION COEFFICIENTS FROM GRIB INPUT 

! -------------------------------------------------------------------

USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
USE YOWDRVTYPE  , ONLY : WVGRIDGLO, WVGRIDLOC

USE YOWABORT , ONLY : WAM_ABORT
USE YOWGRIBINFO, ONLY : WVGETGRIDINFO
USE YOWMAP   , ONLY : NGX, NGY, IPER, IRGG, IQGAUSS, NIBLO,                 &
                   &  DAMOWEP, DAMOSOP, DAMOEAP, DAMONOP, DXDELLA, DXDELLO, &
                   &  NLONRGG
USE YOWMPP   , ONLY : IRANK, NPRECI
USE YOWPARAM , ONLY : NFRE_RED
USE YOWPCONS , ONLY : ZMISS
USE YOWSTAT  , ONLY : IPROPAGS, LSUBGRID
USE YOWSPEC  , ONLY : NSTART, NEND
USE YOWTEST  , ONLY : IU06
USE YOWUBUF  , ONLY : OBSLAT, OBSLON, OBSCOR, OBSRLAT, OBSRLON,  &
                    & NANG_OBS, KTOIS, KTOOBSTRUCT

USE YOWGRIB  , ONLY : IGRIB_GET_VALUE, IGRIB_CLOSE_FILE, IGRIB_RELEASE,     &
                    &  IGRIB_OPEN_FILE, IGRIB_READ_FROM_FILE,                &
                    &  IGRIB_NEW_FROM_MESSAGE, IGRIB_SET_VALUE,              &
                    &  JPKSIZE_T, JPGRIB_BUFFER_TOO_SMALL,                   &
                    &  JPGRIB_END_OF_FILE, JPGRIB_SUCCESS
USE EC_LUN   , ONLY : NULERR
USE MPL_MODULE, ONLY : MPL_BROADCAST
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK

!----------------------------------------------------------------------

IMPLICIT NONE

#include "ktoobs.intfb.h"
#include "wvchkmid.intfb.h"
#include "abort1.intfb.h"

TYPE(WVGRIDGLO), INTENT(IN)       :: BLK2GLO       !! POINTERS FROM GLOBAL GRID POINTS TO 2-D MAP
TYPE(WVGRIDLOC), INTENT(IN)       :: BLK2LOC       !! POINTERS FROM LOCAL GRID POINTS TO 2-D MAP
INTEGER(KIND=JWIM), INTENT(IN)    :: IREAD         !! PE READING THE GRIB FILE
INTEGER(KIND=JWIM), INTENT(IN)    :: NPR           !! NUMBER OF SUBDOMAINS (USUALLY THE NUMBER OF PE'S )
CHARACTER(LEN=*),   INTENT(IN)    :: FILNM         !! FILENAME ASSOCIATED TO GRIB HANDLES
INTEGER(KIND=JWIM), INTENT(INOUT) :: KFILE_HANDLE  !! GRIB FILE HANDLE CONNECTED TO SUB GRIB BATHY INPUT
INTEGER(KIND=JWIM), INTENT(INOUT) :: KGRIB_HANDLE  !! GRIB HANDLE CONNECTED TO SUB GRIB BATHY INPUT

INTEGER(KIND=JWIM) :: IJ, M, K, IS, IX, IY, L, JSN
INTEGER(KIND=JWIM) :: IANGNB, IFRENB, IOBSRT, IFILE_HANDLE
INTEGER(KIND=JWIM) :: IRET, IERR, IEDITION, IGRIB_VERSION
INTEGER(KIND=JWIM) :: NGX_SUB, NGY_SUB, IPER_SUB, IRGG_SUB, IQGAUSS_SUB
INTEGER(KIND=JWIM) :: LFILE, ISIZE, KGRIB_HANDLE_LOC
INTEGER(KIND=JWIM) :: NUMBEROFVALUES
INTEGER(KIND=JWIM), ALLOCATABLE, DIMENSION(:) :: NLONRGG_SUB

! RAW GRIB BATCH BUFFER: NANG_OBS MESSAGES PER FREQUENCY (ALL PES)
INTEGER(KIND=JWIM), ALLOCATABLE :: INGRIB_BATCH(:,:)
INTEGER(KIND=JPKSIZE_T) :: KBYTES

! ROW OFFSETS FOR DIRECT VALUES->SEA-POINT SCATTER
! IROW_OFFSET(K) = SUM OF NLONRGG FOR ALL ROWS ABOVE ROW K (NORTH-TO-SOUTH)
INTEGER(KIND=JWIM), ALLOCATABLE :: IROW_OFFSET(:)

! DECODED VALUES FROM GRIB (REUSABLE PER ANGLE)
REAL(KIND=JWRB), ALLOCATABLE :: VALUES(:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

REAL(KIND=JWRU) ::  AMOWEP_SUB, AMOSOP_SUB, AMOEAP_SUB, AMONOP_SUB, XDELLA_SUB, XDELLO_SUB

LOGICAL :: LLSCANNS_SUB, LLSAMEGRID

! POINTER TO TARGET OBSTRUCTION ARRAY FOR SELECT CASE CONSOLIDATION
REAL(KIND=JWRB), POINTER :: OBS_TARGET(:,:,:)

!----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GETGRBOBSTRCT',0,ZHOOK_HANDLE)

LLSAMEGRID = .TRUE.


! OBSTRUCTION COEFFICIENTS
! NOTE: THEIR VALUES WILL BE RESET IN THE FIRST
! CALL TO PROPAGS TO CONTAIN THE OBSTRUCTION TIME THE GROUP
! VELOCITY At THE INTERFACE !!!!!!!!

IF (ALLOCATED(OBSLON)) DEALLOCATE(OBSLON)
ALLOCATE(OBSLON(NSTART(IRANK):NEND(IRANK),NFRE_RED,2))

IF (ALLOCATED(OBSLAT)) DEALLOCATE(OBSLAT)
ALLOCATE(OBSLAT(NSTART(IRANK):NEND(IRANK),NFRE_RED,2))

IF (IPROPAGS == 1) THEN
  IF (ALLOCATED(OBSRLON)) DEALLOCATE(OBSRLON)
  ALLOCATE(OBSRLON(NSTART(IRANK):NEND(IRANK),NFRE_RED,2))
  IF (ALLOCATED(OBSRLAT)) DEALLOCATE(OBSRLAT)
  ALLOCATE(OBSRLAT(NSTART(IRANK):NEND(IRANK),NFRE_RED,2))
ENDIF

IF (IPROPAGS == 2) THEN
  IF (ALLOCATED(OBSCOR)) DEALLOCATE(OBSCOR)
  ALLOCATE(OBSCOR(NSTART(IRANK):NEND(IRANK),NFRE_RED,4))
ENDIF


IF ( LSUBGRID ) THEN

  CALL KTOOBS(IU06)

  ! BEFORE LOOPING OVER ALL FREQUENCIES, CHECK THAT THE SUBGRID DATA ARE FOR THE SAME GRID
  ! (we will only check the first entry)
  IF (IRANK == IREAD) THEN

    CALL WVCHKMID(IU06, KGRIB_HANDLE,__FILENAME__)

    CALL WVGETGRIDINFO(IU06, KGRIB_HANDLE, &
 &                     NGX_SUB, NGY_SUB, IPER_SUB, IRGG_SUB, IQGAUSS_SUB, NLONRGG_SUB, LLSCANNS_SUB, &
 &                     AMOWEP_SUB, AMOSOP_SUB, AMOEAP_SUB, AMONOP_SUB, XDELLA_SUB, XDELLO_SUB )

    !! Check that it is the same as input BATHY
    CALL IGRIB_GET_VALUE(KGRIB_HANDLE,'editionNumber', IEDITION, IERR)

    IF ( IEDITION == 1 ) THEN
      !! Until we can use the grib2 template for spectra,
      !! we need to limit what can be compared with the grib2 BATHY
      IF ( NGX_SUB /= NGX .OR. NGY_SUB /= NGY .OR. IPER_SUB .NE. IPER .OR. IQGAUSS_SUB .NE. IQGAUSS ) THEN
        LLSAMEGRID = .FALSE.
      ENDIF
    ELSE
      IF ( NGX_SUB /= NGX .OR. NGY_SUB /= NGY .OR. IPER_SUB .NE. IPER .OR. IQGAUSS_SUB .NE. IQGAUSS .OR. &
 &         AMOWEP_SUB /= DAMOWEP .OR. AMOSOP_SUB /= DAMOSOP .OR. AMOEAP_SUB /= DAMOEAP .OR. &
 &          AMONOP_SUB /= DAMONOP .OR. XDELLA_SUB /= DXDELLA .OR. XDELLO_SUB /= DXDELLO ) THEN
        LLSAMEGRID = .FALSE.
      ENDIF
    ENDIF

    IF ( LLSAMEGRID ) THEN
      DO K = 1, NGY
        IF (NLONRGG_SUB(MIN(K,NGY_SUB)) /= NLONRGG(K) ) THEN
            LLSAMEGRID = .FALSE.
           EXIT
        ENDIF
      ENDDO
    ENDIF

    IF( .NOT. LLSAMEGRID ) THEN
      WRITE(NULERR,*) "GETGRBOBSTRCT : " 
      WRITE(NULERR,*) "MEAN AND SUBGRIB BATHYMETRY DO NOT HAVE THE SAME GRID !" 
      WRITE(IU06,*) "GETGRBOBSTRCT : " 
      WRITE(IU06,*) "MEAN AND SUBGRIB BATHYMETRY DO NOT HAVE THE SAME GRID !" 
      WRITE(IU06,*)  NGX, NGY, IPER, IRGG, IQGAUSS
      WRITE(IU06,*)  NGX_SUB, NGY_SUB, IPER_SUB, IRGG_SUB, IQGAUSS_SUB
      DO K = 1, NGY
        WRITE(IU06,*)  K, NLONRGG(K), NLONRGG_SUB(MIN(K,NGY_SUB))
      ENDDO
      WRITE(IU06,*) DAMOWEP, DAMOSOP, DAMOEAP, DAMONOP, DXDELLA, DXDELLO
      WRITE(IU06,*) AMOWEP_SUB, AMOSOP_SUB, AMOEAP_SUB, AMONOP_SUB, XDELLA_SUB, XDELLO_SUB
      CALL FLUSH(IU06)
      CALL WAM_ABORT("Not same grid !",__FILENAME__,__LINE__)
    ENDIF

    CALL IGRIB_CLOSE_FILE(KFILE_HANDLE)
    CALL IGRIB_RELEASE(KGRIB_HANDLE)

    ! OPEN THE GRIB FILE ON PE IREAD
    LFILE = LEN_TRIM(FILNM)
    CALL IGRIB_OPEN_FILE(IFILE_HANDLE, FILNM(1:LFILE), 'r')
    WRITE(IU06,*) ' SUB. GETGRBOBSTRCT - READ FROM ', FILNM(1:LFILE)

  ENDIF ! IRANK == IREAD

  ! PRECOMPUTE ROW OFFSETS FOR DIRECT VALUES -> SEA-POINT SCATTER.
  ! GRIB VALUES ARE STORED NORTH-TO-SOUTH. IN GRIB2WGRID'S MAPPING,
  ! FIELD INDEX K (1=NORTH, NGY=SOUTH) MAPS TO GEOGRAPHIC ROW JSN=NGY-K+1.
  ! FOR ROW K, THE STARTING OFFSET IN VALUES IS:
  !   IROW_OFFSET(K) = SUM_{J=1}^{K-1} NLONRGG(NGY-J+1)
  ! THEN VALUES(IROW_OFFSET(K) + IX) = FIELD(IX, K).
  !
  ! BLK2GLO%KXLT IS SOUTH-TO-NORTH (1=SOUTH, NGY=NORTH).
  ! SO FOR SEA POINT IJ: IY = NGY - BLK2GLO%KXLT(IJ) + 1 (NORTH-TO-SOUTH)
  ! AND THE VALUES INDEX IS: L = IROW_OFFSET(IY) + BLK2GLO%IXLG(IJ)
  ALLOCATE(IROW_OFFSET(NGY))
  IROW_OFFSET(1) = 0
  DO K = 2, NGY
    JSN = NGY - (K-1) + 1   ! GEOGRAPHIC ROW FOR FIELD INDEX K-1
    IROW_OFFSET(K) = IROW_OFFSET(K-1) + NLONRGG(JSN)
  ENDDO

  ! ALLOCATE RAW GRIB BATCH BUFFER (ALL PES NEED IT FOR BROADCAST)
  ISIZE = NIBLO
  ALLOCATE(INGRIB_BATCH(ISIZE, NANG_OBS))

  DO M = 1, NFRE_RED ! loop over frequencies

    ! ---- PE IREAD: READ NANG_OBS RAW GRIB MESSAGES ----
    IF (IRANK == IREAD) THEN
      DO K = 1, NANG_OBS
        KBYTES = ISIZE * NPRECI
        CALL IGRIB_READ_FROM_FILE(IFILE_HANDLE, INGRIB_BATCH(:,K), KBYTES, IRET)

        IF (IRET == JPGRIB_BUFFER_TOO_SMALL) THEN
          WRITE(IU06,*) '****************************************************'
          WRITE(IU06,*) '* GETGRBOBSTRCT: BUFFER TOO SMALL'
          WRITE(IU06,*) '* FREQUENCY M=', M, ' ANGLE K=', K
          WRITE(NULERR,*) '* GETGRBOBSTRCT: BUFFER TOO SMALL'
          WRITE(IU06,*) '****************************************************'
          CALL ABORT1
        ELSEIF (IRET == JPGRIB_END_OF_FILE) THEN
          WRITE(IU06,*) '**********************************'
          WRITE(IU06,*) '* GETGRBOBSTRCT: END OF FILE ENCOUNTERED'
          WRITE(IU06,*) '* FREQUENCY M=', M, ' ANGLE K=', K
          WRITE(NULERR,*) '* GETGRBOBSTRCT: END OF FILE ENCOUNTERED'
          WRITE(IU06,*) '**********************************'
          CALL ABORT1
        ELSEIF (IRET /= JPGRIB_SUCCESS) THEN
          WRITE(IU06,*) '**********************************'
          WRITE(IU06,*) '* GETGRBOBSTRCT: FILE HANDLING ERROR'
          WRITE(IU06,*) '* FREQUENCY M=', M, ' ANGLE K=', K
          WRITE(NULERR,*) '* GETGRBOBSTRCT: FILE HANDLING ERROR'
          WRITE(IU06,*) '**********************************'
          CALL ABORT1
        ENDIF
      ENDDO
    ENDIF

    ! ---- BROADCAST RAW GRIB BATCH TO ALL PES ----
    IF (NPR > 1) THEN
      CALL GSTATS(619,0)
      CALL MPL_BROADCAST(INGRIB_BATCH(:,:), KROOT=IREAD, KTAG=2, &
 &                       CDSTRING='GETGRBOBSTRCT: RAW GRIB BATCH')
      CALL GSTATS(619,1)
    ENDIF

    ! ---- ALL PES: DECODE AND SCATTER EACH ANGLE IN PARALLEL ----
    ! EACH THREAD HANDLES ONE ANGLE (NANG_OBS=8 MATCHES THREAD COUNT).
    ! REQUIRES ECCODES BUILT WITH ECCODES_OMP_THREADS=ON FOR THREAD SAFETY.
!$OMP PARALLEL DO SCHEDULE(STATIC) &
!$OMP&  PRIVATE(K, KGRIB_HANDLE_LOC, IGRIB_VERSION, IANGNB, IFRENB, IERR, &
!$OMP&          IS, IOBSRT, NUMBEROFVALUES, VALUES, OBS_TARGET, &
!$OMP&          IJ, IX, IY, L)
    DO K = 1, NANG_OBS

      ! DECODE GRIB MESSAGE: CREATE HANDLE FROM RAW BYTES
      KGRIB_HANDLE_LOC = -99
      CALL IGRIB_NEW_FROM_MESSAGE(KGRIB_HANDLE_LOC, INGRIB_BATCH(:,K))

      ! EXTRACT DIRECTION AND FREQUENCY NUMBERS FOR VERIFICATION
      CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'editionNumber', IGRIB_VERSION)
      IF (IGRIB_VERSION == 1) THEN
        CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'directionNumber', IANGNB, IERR)
        IF (IERR /= 0) IANGNB = 0
        CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'frequencyNumber', IFRENB, IERR)
        IF (IERR /= 0) IFRENB = 0
      ELSE
        CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'waveDirectionNumber', IANGNB, IERR)
        IF (IERR /= 0) IANGNB = 0
        CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'waveFrequencyNumber', IFRENB, IERR)
        IF (IERR /= 0) IFRENB = 0
      ENDIF

      ! VERIFY EXPECTED ORDER
      IF (IANGNB /= K .OR. IFRENB /= M) THEN
!$OMP   CRITICAL
        WRITE(IU06,*) "GETGRBOBSTRCT : "
        WRITE(IU06,*) "INPUT OBSTRUCTIONS NOT IN THE EXPECTED ORDER !"
        WRITE(IU06,*) "IANGNB, K = ", IANGNB, K
        WRITE(IU06,*) "IFRENB, M = ", IFRENB, M
        CALL FLUSH(IU06)
!$OMP   END CRITICAL
        CALL WAM_ABORT("Obstruction input is NOT in the expected order !",__FILENAME__,__LINE__)
      ENDIF

      IS = KTOIS(K,IPROPAGS)
      IF (IS > 0) THEN
        IOBSRT = KTOOBSTRUCT(K,IPROPAGS)

        ! DECOMPRESS GRIB VALUES (THE EXPENSIVE OPERATION - NOW PARALLEL ACROSS ANGLES)
        CALL IGRIB_SET_VALUE(KGRIB_HANDLE_LOC, 'missingValue', ZMISS)

        IF (IGRIB_VERSION == 1) THEN
          CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'numberOfEffectiveValues', NUMBEROFVALUES)
        ELSE
          CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'getNumberOfValues', NUMBEROFVALUES)
        ENDIF

        ALLOCATE(VALUES(NUMBEROFVALUES))

        CALL IGRIB_GET_VALUE(KGRIB_HANDLE_LOC, 'values', VALUES)

        ! SELECT TARGET ARRAY VIA POINTER TO AVOID DUPLICATED LOOPS
        NULLIFY(OBS_TARGET)
        SELECT CASE(IOBSRT)
        CASE(1)
          OBS_TARGET => OBSLAT
        CASE(2)
          OBS_TARGET => OBSLON
        CASE(3)
          OBS_TARGET => OBSRLAT
        CASE(4)
          OBS_TARGET => OBSRLON
        CASE(5)
          OBS_TARGET => OBSCOR
        END SELECT

        IF (ASSOCIATED(OBS_TARGET)) THEN
          ! SCATTER DIRECTLY FROM VALUES INTO OBS* ARRAYS USING BLK2GLO AND ROW OFFSETS
          ! EACH THREAD WRITES TO DIFFERENT IS SLICE, SO NO WRITE CONFLICTS.
          DO IJ = NSTART(IRANK), NEND(IRANK)
            IX = BLK2GLO%IXLG(IJ)
            IY = NGY - BLK2GLO%KXLT(IJ) + 1
            L = IROW_OFFSET(IY) + IX
            IF (VALUES(L) /= ZMISS) THEN
              OBS_TARGET(IJ,M,IS) = VALUES(L)
            ELSE
              OBS_TARGET(IJ,M,IS) = 1.0_JWRB
            ENDIF
          ENDDO
        ENDIF

        DEALLOCATE(VALUES)

      ENDIF

      CALL IGRIB_RELEASE(KGRIB_HANDLE_LOC)

    ENDDO ! K loop (angles)
!$OMP END PARALLEL DO
  ENDDO ! M loop (frequencies)

  DEALLOCATE(INGRIB_BATCH)
  DEALLOCATE(IROW_OFFSET)
  IF (IRANK == IREAD) THEN
    IF (IFILE_HANDLE > 0) CALL IGRIB_CLOSE_FILE(IFILE_HANDLE)
  ENDIF

  WRITE(IU06,*) ''
  WRITE(IU06,*) ' OBSTRUCTION COEFFICIENTS FROM GRIB INPUT READ IN'
  CALL FLUSH(IU06)

ELSE

  !! No obstructions. By-pass the reading of the obstruction coefficients
  OBSLAT(:,:,:) = 1.0_JWRB
  OBSLON(:,:,:) = 1.0_JWRB
  IF (IPROPAGS == 1) THEN
    OBSRLAT(:,:,:) = 1.0_JWRB
    OBSRLON(:,:,:) = 1.0_JWRB
  ENDIF
  IF (IPROPAGS == 2) THEN
    OBSCOR(:,:,:) = 1.0_JWRB
  ENDIF

ENDIF

!$acc update device(OBSLAT, OBSCOR, OBSLON)

IF (LHOOK) CALL DR_HOOK('GETGRBOBSTRCT',1,ZHOOK_HANDLE)

END SUBROUTINE GETGRBOBSTRCT
