! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE NEWWIND (CDATE, CDATEWH, LLNEWFILE,           &
 &                  WVPRPT, FF_NOW, FF_NEXT)
! ----------------------------------------------------------------------

!**** *NEWWIND* - HANDLING OF WINDS OUTSIDE MULTITASKED AREA    

!     P.A.E.M. JANSSEN  KNMI/ECMWF  SEPTEMBER 1994
!     J. BIDLOT         ECMWF       FEBRUARY 1996  MESSAGE PASSING 
!     S. ABDALLA        ECMWF       OCTOBER 2001   INCLUSION OF AIR
!                                                  DENSITY AND Zi/L
!     J. BIDLOT         ECMWF       AUGUST 2008: CLEAN-UP 

!*    PURPOSE.
!     --------

!       GETS FORCING FIELDS WHEN NEEDED.                                   

!**   INTERFACE.
!     ----------

!       *CALL* *NEWWIND (CDATE, CDATEWH, LLNEWFILE,
!                        WVPRPT, FF_NOW, FF_NEXT,
!      *CDATE*    - START DATE OF SOURCE FUNCTION INTEGRATION
!      *CDATEWH*  - DATE OF THE NEXT FORCING FIELDS
!      *LLNEWFILE*- TRUE IF NEW WIND FILE HAS BEEN OPENED
!      *WVPRPT*   - WAVE PROPERTIES FIELDS
!      *FF_NOW*   - DATA STRUCTURE WITH THE CURRENT FORCING FIELDS
!      *FF_NEXT*  - DATA STRUCTURE WITH THE NEXT FORCING FIELDS

!     METHOD.
!     -------

!       READ NEW WINDS AND ASSOCIATED FIELDS WHEN NEEDED.

!     EXTERNALS.
!     ---------

!       *INCDATE*   - UPDATE DATE TIME GROUP.

!     REFERENCE.
!     ----------

!       NONE

! ----------------------------------------------------------------------

!*    *PARAMETER*  FOR ARRAY DIMENSIONS.

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
      USE YOWDRVTYPE  , ONLY : FREQUENCY, FORCING_FIELDS

      USE YOWPCONS , ONLY : ACD      ,BCD      ,EPSMIN
      USE YOWCOUP  , ONLY : LWCOU
      USE YOWGRID  , ONLY : NPROMA_WAM, NCHNK
      USE YOWPARAM , ONLY : NFRE
      USE YOWPHYS  , ONLY : ALPHA
      USE YOWSTAT  , ONLY : IDELWO
      USE YOWTEST  , ONLY : IU06
      USE YOWWIND  , ONLY : CDATEWL  ,CDAWIFL  ,CDATEFL  ,CDTNEXT  ,         &
     &                      NSTORE   ,WSPMIN_RESET_TAUW  ,USTMIN_RESET_TAUW
      USE YOWWNDG  , ONLY : ICODE    ,ICODE_CPL

      USE YOMHOOK  , ONLY : LHOOK,   DR_HOOK, JPHOOK

! ----------------------------------------------------------------------

      IMPLICIT NONE

#include "abort1.intfb.h"
#ifdef WAM_GPU
#include "cireduce_loki_gpu.intfb.h"
#else
#include "cireduce.intfb.h"
#endif
#include "incdate.intfb.h"

      CHARACTER(LEN=14), INTENT(IN)    :: CDATE
      CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH
      LOGICAL, INTENT(INOUT)           :: LLNEWFILE
      TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT
      TYPE(FORCING_FIELDS), INTENT(INOUT)  :: FF_NOW
      TYPE(FORCING_FIELDS), INTENT(IN)     :: FF_NEXT


      INTEGER(KIND=JWIM) :: ICODE_WND
      INTEGER(KIND=JWIM) :: ICHNK, KIJS, KIJL, IJ

      REAL(KIND=JWRB) :: WGHT, TLWMAX
      REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTRA_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTRA_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUW_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC_NOW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CHRNCK_NOW(:,:) => NULL()

      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTRA_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTRA_NEXT(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC_NEXT(:,:) => NULL()

! ----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('NEWWIND',0,ZHOOK_HANDLE)

      IF (LWCOU) THEN
        ICODE_WND = ICODE_CPL
      ELSE
        ICODE_WND = ICODE
      ENDIF

      WGHT = 1.0_JWRB/MAX(WSPMIN_RESET_TAUW,EPSMIN)

      IF (CDATE >= CDATEWH) THEN

#ifdef WAM_GPU
      CALL NEWWIND_OFFLOAD()
#else
      CALL NEWWIND_SET_POINTERS()
#endif

!*    2. NEW WIND INPUT.
!        ---------------
        IF (CDATE >= CDATEFL) THEN
            LLNEWFILE = .TRUE.
        ENDIF

!*    2.2 NEW WINDS ARE READ IN.
!         ----------------------

        CDATEWL = CDTNEXT

        CALL GSTATS(1492,0)
#ifdef WAM_GPU
#ifdef OMPGPU
!$omp target teams distribute thread_limit( NPROMA_WAM ) private(KIJS,KIJL) &
!$omp & map(to:WSWAVE_NOW,WSWAVE_NEXT,TAUW_NOW,UFRIC_NOW,UFRIC_NEXT,TAUW_NOW,CHRNCK_NOW,WDWAVE_NOW,WDWAVE_NEXT, &
!$omp & AIRD_NOW,AIRD_NEXT,WSTAR_NOW,WSTAR_NEXT,CICOVER_NOW,CICOVER_NEXT,CITHICK_NOW,CITHICK_NEXT, &
!$omp & USTRA_NOW,USTRA_NEXT,VSTRA_NOW,VSTRA_NEXT)
#else
!$acc parallel loop gang private(KIJS,KIJL) vector_length(NPROMA_WAM) &
!$acc & present(WSWAVE_NOW,WSWAVE_NEXT,TAUW_NOW,UFRIC_NOW,UFRIC_NEXT,TAUW_NOW,CHRNCK_NOW,WDWAVE_NOW,WDWAVE_NEXT, &
!$acc & AIRD_NOW,AIRD_NEXT,WSTAR_NOW,WSTAR_NEXT,CICOVER_NOW,CICOVER_NEXT,CITHICK_NOW,CITHICK_NEXT, &
!$acc & USTRA_NOW,USTRA_NEXT,VSTRA_NOW,VSTRA_NEXT)
#endif
#else
!$OMP   PARALLEL DO SCHEDULE(STATIC) PRIVATE(ICHNK, KIJS, KIJL, IJ, TLWMAX)
#endif
        DO ICHNK = 1, NCHNK
          KIJS = 1
          KIJL = NPROMA_WAM
          IF (ICODE_WND == 3 ) THEN
#ifdef OMPGPU
            !$omp parallel do
#else
            !$acc loop vector
#endif
            DO IJ = KIJS, KIJL
              WSWAVE_NOW(IJ,ICHNK) = WSWAVE_NEXT(IJ,ICHNK)
! adapt first estimate of wave induced stress for low winds
! to a fraction of the simple relation u*^2 = Cd(U10) * U10^2
! where this fraction varies from 0 for U10=0 to 1 for U10=WSPMIN_RESET_TAUW
              IF (WSWAVE_NOW(IJ,ICHNK) < WSPMIN_RESET_TAUW) THEN
                TLWMAX = WGHT * (ACD+BCD*WSWAVE_NOW(IJ,ICHNK)) * WSWAVE_NOW(IJ,ICHNK)**3
                TAUW_NOW(IJ,ICHNK) = MIN(TAUW_NOW(IJ,ICHNK), TLWMAX)
              ENDIF
            ENDDO
          ELSE
#ifdef OMPGPU
            !$omp parallel do
#else
            !$acc loop vector
#endif
            DO IJ = KIJS, KIJL
              UFRIC_NOW(IJ,ICHNK) = UFRIC_NEXT(IJ,ICHNK)
! update the estimate of TAUW
              TAUW_NOW(IJ,ICHNK) = UFRIC_NOW(IJ,ICHNK)**2 * (1.0_JWRB-(ALPHA/CHRNCK_NOW(IJ,ICHNK))**2)
! adapt first estimate of wave induced stress for low winds
              IF (UFRIC_NOW(IJ,ICHNK) < USTMIN_RESET_TAUW) TAUW_NOW(IJ,ICHNK) = 0.0_JWRB
            ENDDO
          ENDIF

#ifdef OMPGPU
          !$omp parallel do
#else
          !$acc loop vector
#endif
          DO IJ = KIJS, KIJL
            WDWAVE_NOW(IJ,ICHNK)  = WDWAVE_NEXT(IJ,ICHNK)
            AIRD_NOW(IJ,ICHNK)    = AIRD_NEXT(IJ,ICHNK)
            WSTAR_NOW(IJ,ICHNK)   = WSTAR_NEXT(IJ,ICHNK)
            CICOVER_NOW(IJ,ICHNK) = CICOVER_NEXT(IJ,ICHNK)
            CITHICK_NOW(IJ,ICHNK) = CITHICK_NEXT(IJ,ICHNK)
            USTRA_NOW(IJ,ICHNK)   = USTRA_NEXT(IJ,ICHNK)
            VSTRA_NOW(IJ,ICHNK)   = VSTRA_NEXT(IJ,ICHNK)
          ENDDO

        ENDDO
#ifdef WAM_GPU
#ifdef OMPGPU
!$omp end target teams distribute
#else
!$acc end parallel loop
#endif
#else
!$OMP   END PARALLEL DO
#endif
        CALL GSTATS(1492,1)


        CALL INCDATE(CDATEWH, IDELWO)

!       UPDATE THE SEA ICE REDUCTION FACTOR
#ifdef WAM_GPU
        CALL CIREDUCE_LOKI_GPU (WVPRPT, FF_NOW)
#else
        CALL CIREDUCE (WVPRPT, FF_NOW)
#endif

      ENDIF

IF (LHOOK) CALL DR_HOOK('NEWWIND',1,ZHOOK_HANDLE)
      CONTAINS

      SUBROUTINE NEWWIND_OFFLOAD()

        CALL FF_NOW%F_WDWAVE%GET_DEVICE_DATA_RDWR(WDWAVE_NOW)
        CALL FF_NOW%F_WSWAVE%GET_DEVICE_DATA_RDWR(WSWAVE_NOW)
        CALL FF_NOW%F_AIRD%GET_DEVICE_DATA_RDWR(AIRD_NOW)
        CALL FF_NOW%F_WSTAR%GET_DEVICE_DATA_RDWR(WSTAR_NOW)
        CALL FF_NOW%F_CICOVER%GET_DEVICE_DATA_RDWR(CICOVER_NOW)
        CALL FF_NOW%F_CITHICK%GET_DEVICE_DATA_RDWR(CITHICK_NOW)
        CALL FF_NOW%F_USTRA%GET_DEVICE_DATA_RDWR(USTRA_NOW)
        CALL FF_NOW%F_VSTRA%GET_DEVICE_DATA_RDWR(VSTRA_NOW)
        CALL FF_NOW%F_UFRIC%GET_DEVICE_DATA_RDWR(UFRIC_NOW)
        CALL FF_NOW%F_TAUW%GET_DEVICE_DATA_RDWR(TAUW_NOW)
        CALL FF_NOW%F_CHRNCK%GET_DEVICE_DATA_RDWR(CHRNCK_NOW)

        CALL FF_NEXT%F_WDWAVE%GET_DEVICE_DATA_RDWR(WDWAVE_NEXT)
        CALL FF_NEXT%F_WSWAVE%GET_DEVICE_DATA_RDWR(WSWAVE_NEXT)
        CALL FF_NEXT%F_AIRD%GET_DEVICE_DATA_RDWR(AIRD_NEXT)
        CALL FF_NEXT%F_WSTAR%GET_DEVICE_DATA_RDWR(WSTAR_NEXT)
        CALL FF_NEXT%F_CICOVER%GET_DEVICE_DATA_RDWR(CICOVER_NEXT)
        CALL FF_NEXT%F_CITHICK%GET_DEVICE_DATA_RDWR(CITHICK_NEXT)
        CALL FF_NEXT%F_USTRA%GET_DEVICE_DATA_RDWR(USTRA_NEXT)
        CALL FF_NEXT%F_VSTRA%GET_DEVICE_DATA_RDWR(VSTRA_NEXT)
        CALL FF_NEXT%F_UFRIC%GET_DEVICE_DATA_RDWR(UFRIC_NEXT)

      END SUBROUTINE NEWWIND_OFFLOAD

      SUBROUTINE NEWWIND_SET_POINTERS()

        CALL FF_NOW%F_WDWAVE%GET_HOST_DATA_RDWR(WDWAVE_NOW)
        CALL FF_NOW%F_WSWAVE%GET_HOST_DATA_RDWR(WSWAVE_NOW)
        CALL FF_NOW%F_AIRD%GET_HOST_DATA_RDWR(AIRD_NOW)
        CALL FF_NOW%F_WSTAR%GET_HOST_DATA_RDWR(WSTAR_NOW)
        CALL FF_NOW%F_CICOVER%GET_HOST_DATA_RDWR(CICOVER_NOW)
        CALL FF_NOW%F_CITHICK%GET_HOST_DATA_RDWR(CITHICK_NOW)
        CALL FF_NOW%F_USTRA%GET_HOST_DATA_RDWR(USTRA_NOW)
        CALL FF_NOW%F_VSTRA%GET_HOST_DATA_RDWR(VSTRA_NOW)
        CALL FF_NOW%F_UFRIC%GET_HOST_DATA_RDWR(UFRIC_NOW)
        CALL FF_NOW%F_TAUW%GET_HOST_DATA_RDWR(TAUW_NOW)
        CALL FF_NOW%F_CHRNCK%GET_HOST_DATA_RDWR(CHRNCK_NOW)

        CALL FF_NEXT%F_WDWAVE%GET_HOST_DATA_RDWR(WDWAVE_NEXT)
        CALL FF_NEXT%F_WSWAVE%GET_HOST_DATA_RDWR(WSWAVE_NEXT)
        CALL FF_NEXT%F_AIRD%GET_HOST_DATA_RDWR(AIRD_NEXT)
        CALL FF_NEXT%F_WSTAR%GET_HOST_DATA_RDWR(WSTAR_NEXT)
        CALL FF_NEXT%F_CICOVER%GET_HOST_DATA_RDWR(CICOVER_NEXT)
        CALL FF_NEXT%F_CITHICK%GET_HOST_DATA_RDWR(CITHICK_NEXT)
        CALL FF_NEXT%F_USTRA%GET_HOST_DATA_RDWR(USTRA_NEXT)
        CALL FF_NEXT%F_VSTRA%GET_HOST_DATA_RDWR(VSTRA_NEXT)
        CALL FF_NEXT%F_UFRIC%GET_HOST_DATA_RDWR(UFRIC_NEXT)

      END SUBROUTINE NEWWIND_SET_POINTERS

END SUBROUTINE NEWWIND
