! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE OUTBS_LOKI_GPU (MIJ, FL1, XLLWS,                            &
 &                WVPRPT, WVENVI, FF_NOW, INTFLDS, NEMO2WAM,  &
 &                BOUT)
! ----------------------------------------------------------------------

!**** *OUTBS* - MODEL OUTPUT FROM BLOCK TO FILE, PRINTER AND COMMON.

!*    PURPOSE.
!     --------

!       CONTROL OUTPUT OF WAVE AND WIND FIELDS (except spectrum).

!**   INTERFACE.
!     ----------
!      *CALL*OUTBS (MIJ, FL1, XLLWS,
!                   WVPRPT, WVENVI, FF_NOW, INTFLDS, NEMO2WAM, BOUT)
!      *MIJ*     - LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE.
!      *FL1*     - INPUT SPECTRUM.
!      *XLLWS*   - WINDSEA MASK FROM INPUT SOURCE TERM
!      *WVENVI*  - WAVE ENVIRONMENT (depth, currents,...)
!      *FF_NOW*  - FORCING FIELDS
!      *INTFLDS* - INTEGRATED/DERIVED PARAMETERS
!      *NEMO2WAM*- FIELDS FRON OCEAN MODEL to WAM
!      *BOUT*    - OUTPUT PARAMETERS BUFFER 



!     EXTERNALS.
!     ----------

!       *OUTBLOCK*  - GET ALL OUTPUT PARAMETERS
!   
!     METHOD.
!     -------

!       NONE.

!     REFERENCE.
!     ----------

!       NONE.

! ----------------------------------------------------------------------
      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU, JWRO
      USE YOWDRVTYPE  , ONLY : ENVIRONMENT, FREQUENCY, FORCING_FIELDS,  &
     &                         INTGT_PARAM_FIELDS, OCEAN2WAVE

      USE YOWCOUT  , ONLY : JPPFLAG  ,NIPRMOUT
      USE YOWCOUP  , ONLY : LLNORMWAMOUT
      USE YOWGRID  , ONLY : NPROMA_WAM, NCHNK
      USE YOWPARAM , ONLY : NANG     ,NFRE
      USE YOWSTAT  , ONLY : LUPDATE_GPU_GLOBALS_OUTBS

      USE YOMHOOK  , ONLY : LHOOK,   DR_HOOK, JPHOOK

! ----------------------------------------------------------------------
      IMPLICIT NONE

#include "outblock.intfb.h"
#include "outwnorm.intfb.h"

      INTEGER(KIND=JWIM), DIMENSION(NPROMA_WAM, NCHNK), INTENT(IN)          :: MIJ
      REAL(KIND=JWRB), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK), INTENT(IN) :: FL1
      REAL(KIND=JWRB), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK), INTENT(IN) :: XLLWS
      TYPE(FREQUENCY), INTENT(IN)                                           :: WVPRPT
      TYPE(ENVIRONMENT), INTENT(IN)                                         :: WVENVI
      TYPE(FORCING_FIELDS), INTENT(IN)                                      :: FF_NOW
      TYPE(INTGT_PARAM_FIELDS), INTENT(IN)                                  :: INTFLDS
      TYPE(OCEAN2WAVE), INTENT(IN)                                          :: NEMO2WAM
      REAL(KIND=JWRB), DIMENSION(NPROMA_WAM, NIPRMOUT, NCHNK), INTENT(OUT)  :: BOUT

      !... Device pointers
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WAVNUM(:,:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CINV(:,:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CGROUP(:,:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DEPTH(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UCUR(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VCUR(:,:) => NULL()
      INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IODP(:,:) => NULL()

      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUW(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0M(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0B(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CHRNCK(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK(:,:) => NULL()

      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: ALTWH(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CALTWH(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: RALTCOR(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTOKES(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTOKES(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STRNMS(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUXD(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUYD(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCXD(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCYD(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOC(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIOCD(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIEPS(:,:) => NULL()
      REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIAW(:,:) => NULL()

      REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOSST(:,:) => NULL()
      REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOCICOVER(:,:) => NULL()
      REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOCITHICK(:,:) => NULL()
      REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOUCUR(:,:) => NULL()
      REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOVCUR(:,:) => NULL()

      INTEGER(KIND=JWIM) :: ICHNK

      REAL(KIND=JPHOOK) :: ZHOOK_HANDLE, ZHOOK_HANDLE_DATA_OFFLOAD

      LOGICAL :: LDREPROD

! ----------------------------------------------------------------------


!*    1. COMPUTE MEAN PARAMETERS.
!        ------------------------

IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
      CALL OUTBS_OFFLOAD()
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)

!     COMPUTE MEAN PARAMETERS
IF (LUPDATE_GPU_GLOBALS_OUTBS) THEN
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
!$loki update_device
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)
ENDIF

IF (LHOOK) CALL DR_HOOK('OUTBS',0,ZHOOK_HANDLE)
      CALL GSTATS(1502,0)
!$loki structured-data out(BOUT) present(MIJ,FL1,XLLWS,WAVNUM,CINV,CGROUP, &
!$loki &  DEPTH,UCUR,VCUR,IODP,ALTWH,CALTWH,RALTCOR,USTOKES,VSTOKES,STRNMS, &
!$loki &  TAUXD,TAUYD,TAUOCXD,TAUOCYD,TAUOC,PHIOCD,PHIEPS,PHIAW, &
!$loki &  AIRD,WDWAVE,CICOVER,WSWAVE,WSTAR,UFRIC,TAUW,Z0M,Z0B,CHRNCK, &
!$loki &  CITHICK,NEMOSST,NEMOCICOVER,NEMOCITHICK,NEMOUCUR,NEMOVCUR)

      DO ICHNK = 1, NCHNK
        CALL OUTBLOCK(1, NPROMA_WAM, MIJ(:,ICHNK),                        &
     &                FL1(:,:,:,ICHNK), XLLWS(:,:,:,ICHNK),               &
     &                WAVNUM(:,:,ICHNK), CINV(:,:,ICHNK), CGROUP(:,:,ICHNK), &
     &                DEPTH(:,ICHNK), UCUR(:,ICHNK), VCUR(:,ICHNK), &
     &                IODP(:,ICHNK),                               &
     &                ALTWH(:,ICHNK), CALTWH(:,ICHNK), RALTCOR(:,ICHNK), &
     &                USTOKES(:,ICHNK), VSTOKES(:,ICHNK), STRNMS(:,ICHNK), &
     &                TAUXD(:,ICHNK), TAUYD(:,ICHNK), TAUOCXD(:,ICHNK), &
     &                TAUOCYD(:,ICHNK), TAUOC(:,ICHNK), PHIOCD(:,ICHNK), &
     &                PHIEPS(:,ICHNK), PHIAW(:,ICHNK), &
     &                AIRD(:,ICHNK), WDWAVE(:,ICHNK), CICOVER(:,ICHNK), &
     &                WSWAVE(:,ICHNK), WSTAR(:,ICHNK), &
     &                UFRIC(:,ICHNK), TAUW(:,ICHNK), &
     &                Z0M(:,ICHNK), Z0B(:,ICHNK), CHRNCK(:,ICHNK), &
     &                CITHICK(:,ICHNK), &
     &                NEMOSST(:, ICHNK), NEMOCICOVER(:,ICHNK), &
     &                NEMOCITHICK(:, ICHNK), NEMOUCUR(:,ICHNK), &
     &                NEMOVCUR(:, ICHNK), &
     &                BOUT(:,:,ICHNK))
      ENDDO

!$loki end structured-data
      CALL GSTATS(1502,1)

!     PRINT OUT NORMS
!!!1 to do: decide if there are cases where we might want LDREPROD false
      LDREPROD=.TRUE.
      IF (LLNORMWAMOUT) CALL OUTWNORM(LDREPROD, BOUT)

      LUPDATE_GPU_GLOBALS_OUTBS = .FALSE.


IF (LHOOK) CALL DR_HOOK('OUTBS',1,ZHOOK_HANDLE)

      CONTAINS

      SUBROUTINE OUTBS_OFFLOAD()

       CALL WVPRPT%F_WAVNUM%GET_DEVICE_DATA_RDONLY(WAVNUM)
       CALL WVPRPT%F_CINV%GET_DEVICE_DATA_RDONLY(CINV)
       CALL WVPRPT%F_CGROUP%GET_DEVICE_DATA_RDONLY(CGROUP)

       CALL WVENVI%F_DEPTH%GET_DEVICE_DATA_RDONLY(DEPTH)
       CALL WVENVI%F_UCUR%GET_DEVICE_DATA_RDONLY(UCUR)
       CALL WVENVI%F_VCUR%GET_DEVICE_DATA_RDONLY(VCUR)
       CALL WVENVI%F_IODP%GET_DEVICE_DATA_RDONLY(IODP)

       CALL FF_NOW%F_AIRD%GET_DEVICE_DATA_RDONLY(AIRD)
       CALL FF_NOW%F_WDWAVE%GET_DEVICE_DATA_RDONLY(WDWAVE)
       CALL FF_NOW%F_CICOVER%GET_DEVICE_DATA_RDONLY(CICOVER)
       CALL FF_NOW%F_WSWAVE%GET_DEVICE_DATA_RDONLY(WSWAVE)
       CALL FF_NOW%F_WSTAR%GET_DEVICE_DATA_RDONLY(WSTAR)
       CALL FF_NOW%F_UFRIC%GET_DEVICE_DATA_RDONLY(UFRIC)
       CALL FF_NOW%F_TAUW%GET_DEVICE_DATA_RDONLY(TAUW)
       CALL FF_NOW%F_Z0M%GET_DEVICE_DATA_RDONLY(Z0M)
       CALL FF_NOW%F_Z0B%GET_DEVICE_DATA_RDONLY(Z0B)
       CALL FF_NOW%F_CHRNCK%GET_DEVICE_DATA_RDONLY(CHRNCK)
       CALL FF_NOW%F_CITHICK%GET_DEVICE_DATA_RDONLY(CITHICK)

       CALL INTFLDS%F_ALTWH%GET_DEVICE_DATA_RDONLY(ALTWH)
       CALL INTFLDS%F_CALTWH%GET_DEVICE_DATA_RDONLY(CALTWH)
       CALL INTFLDS%F_RALTCOR%GET_DEVICE_DATA_RDONLY(RALTCOR)
       CALL INTFLDS%F_USTOKES%GET_DEVICE_DATA_RDONLY(USTOKES)
       CALL INTFLDS%F_VSTOKES%GET_DEVICE_DATA_RDONLY(VSTOKES)
       CALL INTFLDS%F_STRNMS%GET_DEVICE_DATA_RDONLY(STRNMS)
       CALL INTFLDS%F_TAUXD%GET_DEVICE_DATA_RDONLY(TAUXD)
       CALL INTFLDS%F_TAUYD%GET_DEVICE_DATA_RDONLY(TAUYD)
       CALL INTFLDS%F_TAUOCXD%GET_DEVICE_DATA_RDONLY(TAUOCXD)
       CALL INTFLDS%F_TAUOCYD%GET_DEVICE_DATA_RDONLY(TAUOCYD)
       CALL INTFLDS%F_TAUOC%GET_DEVICE_DATA_RDONLY(TAUOC)
       CALL INTFLDS%F_PHIOCD%GET_DEVICE_DATA_RDONLY(PHIOCD)
       CALL INTFLDS%F_PHIEPS%GET_DEVICE_DATA_RDONLY(PHIEPS)
       CALL INTFLDS%F_PHIAW%GET_DEVICE_DATA_RDONLY(PHIAW)

       CALL NEMO2WAM%F_NEMOSST%GET_DEVICE_DATA_RDONLY(NEMOSST)
       CALL NEMO2WAM%F_NEMOCICOVER%GET_DEVICE_DATA_RDONLY(NEMOCICOVER)
       CALL NEMO2WAM%F_NEMOCITHICK%GET_DEVICE_DATA_RDONLY(NEMOCITHICK)
       CALL NEMO2WAM%F_NEMOUCUR%GET_DEVICE_DATA_RDONLY(NEMOUCUR)
       CALL NEMO2WAM%F_NEMOVCUR%GET_DEVICE_DATA_RDONLY(NEMOVCUR)

      END SUBROUTINE OUTBS_OFFLOAD

END SUBROUTINE OUTBS_LOKI_GPU
