! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE WAMINTGR_LOKI_GPU(CDTPRA, CDATE, CDATEWH, CDTIMP, CDTIMPNEXT,  &
 &                   BLK2GLO,                                     &
 &                   WVENVI, WVPRPT, FF_NOW, FF_NEXT, INTFLDS,    &
 &                   WAM2NEMO, MIJ, VARS_4D)


! ----------------------------------------------------------------------

!**** *WAMINTGR* - 3-G WAM MODEL - TIME INTEGRATION OF WAVE FIELDS.

!*    PURPOSE.
!     --------

!       COMPUTATION OF THE 2-D FREQUENCY-DIRECTION WAVE SPECTRUM AT ALL
!       GRID POINTS FOR A GIVEN INITIAL SPECTRUM AND FORCING SURFACE
!       STRESS FIELD.

!     REFERENCE.
!     ----------

!         IFS DOCUMENTATION, part VII 

! -------------------------------------------------------------------

USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU, JWRO
USE YOWDRVTYPE  , ONLY : WVGRIDGLO, ENVIRONMENT, FREQUENCY, FORCING_FIELDS,  &
 &                       INTGT_PARAM_FIELDS, WAVE2OCEAN, MIJ_TYPE, TYPE_4D

USE YOWCOUP  , ONLY : LWNEMOCOU, NEMONTAU
USE YOWGRID  , ONLY : NPROMA_WAM, NCHNK
USE YOWPARAM , ONLY : NANG, NFRE
USE YOWPCONS , ONLY : EPSMIN
USE YOWSTAT  , ONLY : CDTPRO, IDELPRO, IDELT, IDELWI, LLSOURCE, TIME_PROPAG, TIME_PHYS, &
 &  LUPDATE_GPU_GLOBALS
USE YOWWIND  , ONLY : CDAWIFL, CDATEWO, CDATEFL
USE FIELD_ASYNC_MODULE, ONLY : WAIT_FOR_ASYNC_QUEUE

USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK

! ----------------------------------------------------------------------

IMPLICIT NONE

#include "implsch.intfb.h"
#include "incdate.intfb.h"
#include "newwind.intfb.h"
#include "propag_wam.intfb.h"
#include "wam_user_clock.intfb.h"

CHARACTER(LEN=14), INTENT(IN)                                            :: CDTPRA  ! DATE FOR CALL PROPAGATION
CHARACTER(LEN=14), INTENT(INOUT)                                         :: CDATE  ! CURRENT DATE
CHARACTER(LEN=14), INTENT(INOUT)                                         :: CDATEWH ! DATE OF THE NEXT FORCING FIELDS
CHARACTER(LEN=14), INTENT(INOUT)                                         :: CDTIMP  ! START DATE OF SOURCE FUNCTION INTEGRATION
CHARACTER(LEN=14), INTENT(INOUT)                                         :: CDTIMPNEXT  ! NEXT START DATE OF SOURCE FUNCTION INTEGRATION
TYPE(WVGRIDGLO), INTENT(IN)                                              :: BLK2GLO  ! BLOCK TO GRID TRANSFORMATION
TYPE(ENVIRONMENT), INTENT(INOUT)                                         :: WVENVI !  WAVE ENVIRONMENT FIELDS
TYPE(FREQUENCY), INTENT(INOUT)                                           :: WVPRPT  ! WAVE PROPERTIES FIELDS
TYPE(FORCING_FIELDS), INTENT(INOUT)                                      :: FF_NOW  ! FORCING FIELDS AT CURRENT TIME
TYPE(FORCING_FIELDS), INTENT(IN)                                         :: FF_NEXT  !  DATA STRUCTURE WITH THE NEXT FORCING FIELDS
TYPE(INTGT_PARAM_FIELDS), INTENT(INOUT)                                  :: INTFLDS  ! INTEGRATED/DERIVED PARAMETERS
TYPE(WAVE2OCEAN), INTENT(INOUT)                                          :: WAM2NEMO  ! WAVE FIELDS PASSED TO NEMO
TYPE(MIJ_TYPE), INTENT(INOUT)                                            :: MIJ
TYPE(TYPE_4D), INTENT(INOUT)                                             :: VARS_4D

REAL(KIND=JWRB) :: TIME0


INTEGER(KIND=JWIM) :: IJ, K, M
INTEGER(KIND=JWIM) :: ICHNK
INTEGER(KIND=JWIM) :: IDELWH

!... Device pointers
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: FL1(:,:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XLLWS(:,:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WAVNUM(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CGROUP(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: OMOSNH2KD(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DEPTH(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DELLAM1(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: COSPHM1(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UCUR(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VCUR(:,:) => NULL()
INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: MIJ_PTR(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CIWA(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CINV(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XK2CG(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STOKFAC(:,:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: EMAXDPT(:,:) => NULL()
INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IOBND(:,:) => NULL()
INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IODP(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTRA(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTRA(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUW(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUWDIR(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0M(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0B(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CHRNCK(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOUSTOKES(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOVSTOKES(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOSTRN(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NPHIEPS(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NTAUOC(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NSWH(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NMWP(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOTAUX(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOTAUY(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOWSWAVE(:,:) => NULL()
REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOPHIF(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSEMEAN(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSFMEAN(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTOKES(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTOKES(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STRNMS(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUXD(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUYD(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCXD(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCYD(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOC(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIOCD(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIEPS(:,:) => NULL()
REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIAW(:,:) => NULL()

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE, ZHOOK_HANDLE_IMPLSCH, ZHOOK_HANDLE_DATA_OFFLOAD


LOGICAL, SAVE :: LLNEWFILE

DATA LLNEWFILE / .FALSE. /

! ----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('WAMINTGR',0,ZHOOK_HANDLE)

!*     PROPAGATION TIME
!      ----------------

IF(LUPDATE_GPU_GLOBALS)THEN
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
!$loki update_device
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)
ENDIF

IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
!$loki hoist-insert
CALL WAIT_FOR_ASYNC_QUEUE(QUEUE=1)
CALL WAMINTGR_OFFLOAD_1()
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)

#ifdef OMPGPU
!$omp target data map(to:WAVNUM, CGROUP, OMOSNH2KD, FL1, & 
!$omp &               DEPTH, DELLAM1, COSPHM1, UCUR, VCUR)
#else
!$acc data present(WAVNUM, CGROUP, OMOSNH2KD, FL1, & 
!$acc &            DEPTH, DELLAM1, COSPHM1, UCUR, VCUR)
#endif

IF (CDATE == CDTPRA) THEN
  TIME0=-WAM_USER_CLOCK()
  CALL PROPAG_WAM(BLK2GLO, WAVNUM, CGROUP, OMOSNH2KD, FL1,& 
&  DEPTH, DELLAM1, COSPHM1, UCUR, VCUR)
  TIME_PROPAG = TIME_PROPAG + (TIME0+WAM_USER_CLOCK())*1.E-06
  CDATE = CDTPRO
ENDIF
#ifdef OMPGPU
!$omp end target data
#else
!$acc end data
#endif

!* RETRIEVING NEW FORCING FIELDS IF NEEDED.
!  ----------------------------------------
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
CALL WAIT_FOR_ASYNC_QUEUE(QUEUE=2)
IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)
CALL NEWWIND(CDTIMP, CDATEWH, LLNEWFILE,      &
 &           WVPRPT, FF_NOW, FF_NEXT)


! IT IS TIME TO INTEGRATE THE SOURCE TERMS
! ----------------------------------------
IF (CDATE >= CDTIMPNEXT) THEN
! COMPUTE UPDATE DUE TO SOURCE TERMS
  CALL GSTATS(1431,0)
  IF (LLSOURCE) THEN

      IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
      CALL WAIT_FOR_ASYNC_QUEUE(QUEUE=3)
      CALL WAMINTGR_OFFLOAD_2()
      IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)

      IF (LHOOK) CALL DR_HOOK('IMPLSCH',0,ZHOOK_HANDLE_IMPLSCH)
      TIME0=-WAM_USER_CLOCK()

!$loki structured-data present(WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, &
!$loki &  DEPTH, IOBND, IODP, AIRD, WDWAVE, CICOVER,  WSWAVE,WSTAR,  USTRA, VSTRA, &
!$loki &  UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, &
!$loki &  NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, &
!$loki &  WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS, TAUXD, TAUYD, TAUOCXD, &
!$loki & TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW,MIJ_PTR, XLLWS)

      DO ICHNK=1,NCHNK
         CALL IMPLSCH (1, NPROMA_WAM, FL1(:,:,:,ICHNK),   &
 &                     WAVNUM(:,:,ICHNK), CGROUP(:,:,ICHNK), CIWA(:,:,ICHNK), &
 &                     CINV(:,:,ICHNK), XK2CG(:,:,ICHNK), STOKFAC(:,:,ICHNK), &
 &                     EMAXDPT(:,ICHNK), &
 &                     DEPTH(:,ICHNK), IOBND(:,ICHNK), IODP(:,ICHNK), &
 &                     AIRD(:,ICHNK), WDWAVE(:,ICHNK), CICOVER(:,ICHNK), &
 &                     WSWAVE(:,ICHNK),WSTAR(:,ICHNK), &
 &                     USTRA(:,ICHNK), VSTRA(:,ICHNK), &
 &                     UFRIC(:,ICHNK), TAUW(:,ICHNK), TAUWDIR(:,ICHNK), &
 &                     Z0M(:,ICHNK), Z0B(:,ICHNK), CHRNCK(:,ICHNK), &
 &                     CITHICK(:,ICHNK), &
 &                     NEMOUSTOKES(:,ICHNK), NEMOVSTOKES(:,ICHNK), NEMOSTRN(:,ICHNK), &
 &                     NPHIEPS(:,ICHNK), NTAUOC(:,ICHNK), NSWH(:,ICHNK), &
 &                     NMWP(:,ICHNK), NEMOTAUX(:,ICHNK), NEMOTAUY(:,ICHNK), &
 &                     NEMOWSWAVE(:,ICHNK), NEMOPHIF(:,ICHNK), &
 &                     WSEMEAN(:,ICHNK), WSFMEAN(:,ICHNK), &
 &                     USTOKES(:,ICHNK), VSTOKES(:,ICHNK), STRNMS(:,ICHNK), &
 &                     TAUXD(:,ICHNK), TAUYD(:,ICHNK), TAUOCXD(:,ICHNK), &
 &                     TAUOCYD(:,ICHNK), TAUOC(:,ICHNK), PHIOCD(:,ICHNK), &
 &                     PHIEPS(:,ICHNK), PHIAW(:,ICHNK), &
 &                     MIJ_PTR(:,ICHNK), XLLWS(:,:,:,ICHNK) )
      END DO

!$loki end structured-data

      TIME_PHYS = TIME_PHYS + (TIME0+WAM_USER_CLOCK())*1.E-06
      IF (LHOOK) CALL DR_HOOK('IMPLSCH',1,ZHOOK_HANDLE_IMPLSCH)

      IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',0,ZHOOK_HANDLE_DATA_OFFLOAD)
      CALL VARS_4D%SYNC_HOST_RDONLY(FL1=.TRUE., QUEUE=4)
      CALL FF_NOW%SYNC_HOST_RDONLY(QUEUE=4)
      CALL WVENVI%SYNC_HOST_RDONLY(QUEUE=5)
      CALL WAM2NEMO%SYNC_HOST_RDONLY(QUEUE=6)
      IF (LHOOK) CALL DR_HOOK('DATA_OFFLOAD',1,ZHOOK_HANDLE_DATA_OFFLOAD)

    IF (LWNEMOCOU) NEMONTAU = NEMONTAU + 1

  ELSE
!   NO SOURCE TERM CONTRIBUTION
    CALL WAMINTGR_OFFLOAD_3()
#ifdef OMPGPU
!$omp target teams distribute map(to:MIJ_PTR,FL1,XLLWS)
#else
!$acc kernels present(MIJ_PTR,FL1,XLLWS)
#endif
    DO ICHNK = 1, NCHNK
#ifdef OMPGPU
      !$omp parallel do 
#endif
      DO IJ = 1, NPROMA_WAM
        MIJ_PTR(IJ,ICHNK) = NFRE
      ENDDO

#ifdef OMPGPU
      !$omp parallel do collapse(3)
#endif
      DO M = 1, NFRE
        DO K = 1, NANG
          DO IJ = 1, NPROMA_WAM
            FL1(IJ,K,M,ICHNK) = MAX(FL1(IJ,K,M,ICHNK), EPSMIN)
            XLLWS(IJ,K,M,ICHNK) = 0.0_JWRB
          ENDDO
        ENDDO
      ENDDO
    ENDDO
#ifdef OMPGPU
!$omp end target teams distribute
#else
!$acc end kernels
#endif
  ENDIF
  CALL GSTATS(1431,1)



!*       UPDATE FORCING FIELDS TIME COUNTER 
!        ----------------------------------
  IF (LLNEWFILE) THEN
    LLNEWFILE = .FALSE.
    IDELWH = MAX(IDELWI, IDELPRO)
    CALL INCDATE(CDAWIFL, IDELWH)
    CALL INCDATE(CDATEFL, IDELWH)
  ENDIF

  CDATEWO=CDATEWH
  CDTIMP=CDTIMPNEXT
  CALL INCDATE(CDTIMPNEXT, IDELT)   

ENDIF

IF (LHOOK) CALL DR_HOOK('WAMINTGR',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE WAMINTGR_OFFLOAD_1()

  CALL VARS_4D%F_FL1%GET_DEVICE_DATA_RDWR(FL1)

  CALL WVPRPT%F_WAVNUM%GET_DEVICE_DATA_RDWR(WAVNUM)
  CALL WVPRPT%F_CGROUP%GET_DEVICE_DATA_RDWR(CGROUP)
  CALL WVPRPT%F_OMOSNH2KD%GET_DEVICE_DATA_RDWR(OMOSNH2KD)

  CALL WVENVI%F_DEPTH%GET_DEVICE_DATA_RDWR(DEPTH)
  CALL WVENVI%F_DELLAM1%GET_DEVICE_DATA_RDWR(DELLAM1)
  CALL WVENVI%F_COSPHM1%GET_DEVICE_DATA_RDWR(COSPHM1)
  CALL WVENVI%F_UCUR%GET_DEVICE_DATA_RDWR(UCUR)
  CALL WVENVI%F_VCUR%GET_DEVICE_DATA_RDWR(VCUR)

  CALL BLK2GLO%SYNC_DEVICE_RDONLY()

END SUBROUTINE WAMINTGR_OFFLOAD_1

SUBROUTINE WAMINTGR_OFFLOAD_2()

  CALL WVPRPT%F_CIWA%GET_DEVICE_DATA_RDWR(CIWA)
  CALL WVPRPT%F_CINV%GET_DEVICE_DATA_RDWR(CINV)
  CALL WVPRPT%F_XK2CG%GET_DEVICE_DATA_RDWR(XK2CG)
  CALL WVPRPT%F_STOKFAC%GET_DEVICE_DATA_RDWR(STOKFAC)

  CALL WVENVI%F_EMAXDPT%GET_DEVICE_DATA_RDWR(EMAXDPT)
  CALL WVENVI%F_IOBND%GET_DEVICE_DATA_RDWR(IOBND)
  CALL WVENVI%F_IODP%GET_DEVICE_DATA_RDWR(IODP)

  CALL FF_NOW%F_AIRD%GET_DEVICE_DATA_RDWR(AIRD)
  CALL FF_NOW%F_WDWAVE%GET_DEVICE_DATA_RDWR(WDWAVE)
  CALL FF_NOW%F_CICOVER%GET_DEVICE_DATA_RDWR(CICOVER)
  CALL FF_NOW%F_WSWAVE%GET_DEVICE_DATA_RDWR(WSWAVE)
  CALL FF_NOW%F_WSTAR%GET_DEVICE_DATA_RDWR(WSTAR)
  CALL FF_NOW%F_USTRA%GET_DEVICE_DATA_RDWR(USTRA)
  CALL FF_NOW%F_VSTRA%GET_DEVICE_DATA_RDWR(VSTRA)
  CALL FF_NOW%F_UFRIC%GET_DEVICE_DATA_RDWR(UFRIC)
  CALL FF_NOW%F_TAUW%GET_DEVICE_DATA_RDWR(TAUW)
  CALL FF_NOW%F_TAUWDIR%GET_DEVICE_DATA_RDWR(TAUWDIR)
  CALL FF_NOW%F_Z0M%GET_DEVICE_DATA_RDWR(Z0M)
  CALL FF_NOW%F_Z0B%GET_DEVICE_DATA_RDWR(Z0B)
  CALL FF_NOW%F_CHRNCK%GET_DEVICE_DATA_RDWR(CHRNCK)
  CALL FF_NOW%F_CITHICK%GET_DEVICE_DATA_RDWR(CITHICK)

  CALL WAM2NEMO%F_NEMOUSTOKES%GET_DEVICE_DATA_RDWR(NEMOUSTOKES)
  CALL WAM2NEMO%F_NEMOVSTOKES%GET_DEVICE_DATA_RDWR(NEMOVSTOKES)
  CALL WAM2NEMO%F_NEMOSTRN%GET_DEVICE_DATA_RDWR(NEMOSTRN)
  CALL WAM2NEMO%F_NPHIEPS%GET_DEVICE_DATA_RDWR(NPHIEPS)
  CALL WAM2NEMO%F_NTAUOC%GET_DEVICE_DATA_RDWR(NTAUOC)
  CALL WAM2NEMO%F_NSWH%GET_DEVICE_DATA_RDWR(NSWH)
  CALL WAM2NEMO%F_NMWP%GET_DEVICE_DATA_RDWR(NMWP)
  CALL WAM2NEMO%F_NEMOTAUX%GET_DEVICE_DATA_RDWR(NEMOTAUX)
  CALL WAM2NEMO%F_NEMOTAUY%GET_DEVICE_DATA_RDWR(NEMOTAUY)
  CALL WAM2NEMO%F_NEMOWSWAVE%GET_DEVICE_DATA_RDWR(NEMOWSWAVE)
  CALL WAM2NEMO%F_NEMOPHIF%GET_DEVICE_DATA_RDWR(NEMOPHIF)

  CALL INTFLDS%F_WSEMEAN%GET_DEVICE_DATA_RDWR(WSEMEAN)
  CALL INTFLDS%F_WSFMEAN%GET_DEVICE_DATA_RDWR(WSFMEAN)
  CALL INTFLDS%F_USTOKES%GET_DEVICE_DATA_RDWR(USTOKES)
  CALL INTFLDS%F_VSTOKES%GET_DEVICE_DATA_RDWR(VSTOKES)
  CALL INTFLDS%F_STRNMS%GET_DEVICE_DATA_RDWR(STRNMS)
  CALL INTFLDS%F_TAUXD%GET_DEVICE_DATA_RDWR(TAUXD)
  CALL INTFLDS%F_TAUYD%GET_DEVICE_DATA_RDWR(TAUYD)
  CALL INTFLDS%F_TAUOCXD%GET_DEVICE_DATA_RDWR(TAUOCXD)
  CALL INTFLDS%F_TAUOCYD%GET_DEVICE_DATA_RDWR(TAUOCYD)
  CALL INTFLDS%F_TAUOC%GET_DEVICE_DATA_RDWR(TAUOC)
  CALL INTFLDS%F_PHIOCD%GET_DEVICE_DATA_RDWR(PHIOCD)
  CALL INTFLDS%F_PHIEPS%GET_DEVICE_DATA_RDWR(PHIEPS)
  CALL INTFLDS%F_PHIAW%GET_DEVICE_DATA_RDWR(PHIAW)

  CALL MIJ%F_PTR%GET_DEVICE_DATA_RDWR(MIJ_PTR)

  CALL VARS_4D%F_XLLWS%GET_DEVICE_DATA_RDWR(XLLWS)

END SUBROUTINE WAMINTGR_OFFLOAD_2

SUBROUTINE WAMINTGR_OFFLOAD_3()
  CALL MIJ%F_PTR%GET_DEVICE_DATA_RDWR(MIJ_PTR)
  CALL VARS_4D%F_XLLWS%GET_DEVICE_DATA_RDWR(XLLWS)
  CALL VARS_4D%F_FL1%GET_DEVICE_DATA_RDWR(FL1)
END SUBROUTINE WAMINTGR_OFFLOAD_3

END SUBROUTINE WAMINTGR_LOKI_GPU
